force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/recordUrl__c.field-meta.xml
<CustomField>
    <fullName>recordUrl__c</fullName>
    <formula>&apos;https://pmtvsample-developer-edition.ap27.force.com/s/company/&apos; +  Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>recordUrl</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/Job_Openings__c.object-meta.xml
<CustomObject>
    <label>Job Openings</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Openings__c/fields/About_Job__c.field-meta.xml
<CustomField>
    <fullName>About_Job__c</fullName>
    <label>About Job</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/CommunityUrl__c.field-meta.xml
<CustomField>
    <fullName>CommunityUrl__c</fullName>
    <formula>&apos;https://pmtvsample-developer-edition.ap27.force.com/s/job-openings/&apos; +  Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CommunityUrl</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Openings</relationshipLabel>
    <relationshipName>Job_Openings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <label>Job Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>IT Manager</fullName>
            </value>
            <value>
                <fullName>Customer Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification Required</label>
    <length>20000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Job_Openings__c/fields/Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Responsibilities__c</fullName>
    <label>Responsibilities</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/JobController.cls
public without sharing class JobController {
    @AuraEnabled(cacheable=true)
    public static List<Job_Openings__c> getAllJobs(String companyName){ 
        if(companyName=='All'){
            return[ SELECT Name, Company__r.Name, Location__c, CommunityUrl__c FROM Job_Openings__c
                    ORDER BY Name ASC];
        }else{
            return[ SELECT Name, Company__r.Name, Location__c, CommunityUrl__c FROM Job_Openings__c
                    WHERE Company__r.Name = :companyName
                    ORDER BY Name ASC];
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Job_Openings__c> getJobByJobId(Id jobId){
        return [SELECT Name, About_Job__c, Job_Description__c, Qualification_Required__c,
                Responsibilities__c, Company__r.Name, Job_Category__c, Location__c, Company__r.recordUrl__c 
                FROM Job_Openings__c WHERE Id = :jobId];
    }
}